### ISSUE TITLE
go through laml backlog

### ISSUE THREAD

**Issue by pkra** [pkra/laml-wc#2]
What's interesting from https://github.com/pkra/laml/issues ?

* [ ] https://github.com/pkra/laml/issues/50 - check again later
* [ ] https://github.com/pkra/laml/issues/7 - not sure what this was after
* [ ] https://github.com/pkra/laml/issues/11 - in the sense that we haven't touched that subject yet
